### ISSUE TITLE
Is it possible to set the bin width in mcareader?

### ISSUE THREAD

**Issue by Theresa24** [Dih5/mcareader#2]
Hi all,

I'm a new python user and since I use an Amptek detector, your mcareader is simply great.
The only question now is whether it is possible to set the bin width of a histogram?

Thanks and best regards,
Theresa

**Comment by Dih5** [comment]
Hello Theresa, thank you for your comment.

To keep the functionality simple I do not plan to include rebinning, but you can easily perform it after getting the data. I have added two simple examples in the [demo](https://github.com/Dih5/mcareader/blob/master/demos/intro.ipynb). If think they are self explanatory, but feel free to ask if you need to.

**Comment by Theresa24** [comment]
Hi,

thank you very much for your fast reply.
The problem I'm facing at the moment is that I'm trying to evaluate uncalibrated mac-files. Is there an easy option to do this with your code?

Best regards,
Theresa

**Comment by Dih5** [comment]
Even if there is no calibration data in the file, everything will work just the same way.

When you instantiate the Mca object, a warning will be raised to remind channel number is used instead of the energy, so the _y_ coordinates are counts per channel.

**Comment by Theresa24** [comment]
Right, that also works perfectly.

My question was, whether there is an option to calibrate the data during the evaluation, since I'd like to have the energy instead of the channel number.

**Comment by Dih5** [comment]
There is also an option for using custom calibration points, for example
```python
mca.Mca("my/file.mca", calibration=[[120, 6.0], [210, 11.0], [300.0, 15.0]])
```
will associate channel 120 with 6.0 keV (or other consistent unit) and so on. A path to a different mca file with the calibration can also be provided. The [online documentation](http://mcareader.readthedocs.io/en/latest/) lists all the available functionality.

Now, if you want to programmatically find those calibration points, you can do it from Python (just google _python peak detection_ to see how to identify channels with peaks); however, since you'll have to check the results and manually identify the energies, I think it is better to use Amptek's DppMCA to add the calibration to a file and then use it with the _calibration_ option.

**Comment by Theresa24** [comment]
Perfect, that's exactly what I was looking for!
Thank you very much!

**Comment by Dih5** [comment]
:+1:
